apiVersion: v1
kind: Endpoints
metadata:
  name: kube-scheduler
  namespace: monitoring
  labels:
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
    k8s-app: kube-scheduler
subsets:
  - ports:
      - name: "https-metrics"
        port: 10259