apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler
  namespace: monitoring
  labels:
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
    k8s-app: kube-scheduler
spec:
  ports:
    - name: https-metrics
      protocol: TCP
      port: 10259
      targetPort: 10259
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: RequireDualStack
