# Build the manager binary
FROM --platform=$BUILDPLATFORM golang:1.24.4-alpine3.21 AS builder
ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.sum ./

# Cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

COPY assets/ assets/
# Copy the go source
COPY main.go main.go

# Build
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} GO111MODULE=on go build -a -o etcd main.go

# Use alpine base container
FROM alpine:3.22.0

ENV USER_UID=2001 \
    USER_NAME=monitoring-operator \
    GROUP_NAME=monitoring-operator

WORKDIR /
COPY --from=builder --chown=${USER_UID} /workspace/etcd .

RUN addgroup ${GROUP_NAME} && adduser -D -G ${GROUP_NAME} -u ${USER_UID} ${USER_NAME}
USER ${USER_UID}

ENTRYPOINT ["/etcd"]
